[build]
builder = "nixpacks"
buildCommand = "npm run build"

[variables]
NODE_ENV = "production"

[[services]]
name = "web"
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 2

[[services]]
name = "worker"
startCommand = "npm run server"
port = 3001

